### ISSUE TITLE
ch03/jeju_life_location.ipynb 파일에서 파일명이름이 다릅니다.

### ISSUE THREAD

**Issue by pyohamen** [wikibook/dacon#2]
레포지토리의 csv 파일명은
df_location.csv
life_location.csv
인데,

jeju_life_location.ipynb 파일에서
df_location = pd.read_csv('location_df.csv', encoding='cp949')
life_location = pd.read_csv('location_life.csv', encoding='cp949')

으로 되어있네요.

아 그리고 레포지토리의
df_location.csv 와
life_location.csv 파일의
'경도', 'NO' 칼럼이 이미 지오코딩으로 필드명이 바뀌어 있는 상태입니다.
때문에, jeju_life_location.ipynb 파일에서 해당 칼럼을 삭제하는 셀에서 에러가 나네요

**Comment by ychoi-kr** [comment]
이슈 올려주셔서 감사합니다. 저자 분께 전달해 확인 요청 드린 상태입니다.
이력 추적을 위해 이 이슈를 reopen하겠습니다.

**Comment by pyohamen** [comment]
아, Issue #2 은 제가 잘못 보았습니다.
레포지토리의 df_location.csv 와 life_location.csv 파일 과는 별개로

쥬피터 내부에서 location_df.csv 와 location_life.csv 파일을 생성하는 과정이 설명되어 있습니다.

shell by shell 로 수행했다면 해당 이슈를 올리지 않았을 텐데,
run all 을 한 후, 오류를 먼저 찾았기 때문에 잘못된 이슈를 올렸습니다.

closed 하겠습니다. 주말인데 답변감사합니다.
