### ISSUE TITLE
ch3 에서 테이터타입다른것 에 대한 이슈입니다.

### ISSUE THREAD

**Issue by pyohamen** [wikibook/dacon#4]
`ch03/prediction.ipynb` 파일의 3.3 데이터 전처리 하에서

`#학습 데이터와 테스트 데이터를 구분하기 위한 변수 생성`
shell 에서
cue 피쳐에 대해 0, 1 의 타입 은 int 로 되어있는데

아래 3.3.1.1 탐색적 데이터 분석을 통한 변수의
`# 요일별 평균 탑승 승객수를 구하는 함수`
shell 에서는
df.query('cue=="0"') 으로 str 타입이 인덱싱되었습니다.

**Comment by ychoi-kr** [comment]
#2 이슈와 중복되는 내용을 삭제했습니다.
