### ISSUE TITLE
holiday 계산 방법이 맞는건지 질문드립니다.

### ISSUE THREAD

**Issue by anespart1** [wikibook/dacon#6]
`def holiday_function(x):` 에서
`if x in ['2019-09-12', ~ , '2019-10-09']:`이면 `return 1`,
`else:`이면 `return 0` 으로 되어 있습니다만,

실제로 해보면 그냥 전부 0으로 통일되어서 나옵니다.
제 생각에 x는 datetime, 리스트 안의 날짜값은 str로 서로 dtype이 달라 발생하는 문제로 보입니다.
해당 부분에서 `if str(x) in []:` 을 해보았지만 안되길래, 저는 리스트를 datetime으로 바꾸어 해결했습니다.
제 지식이 부족하다보니, 혹시 더 나은 방법이 있는지 문의 드립니다.

**Comment by vcnc-kristoff** [comment]
안녕하세요 책 저자입니다. anespart1 님께서 해주신 방법대로 리스트를 datetime 으로 처리하시는 방법이 가장 효과적인 방법인 것 같습니다.
